- name: create Jenkins jobs
  hosts: all
  tasks:
    - name: Create a jenkins job
      community.general.jenkins_job:
        config: "{{ lookup('file', 'test.xml') }}"
        name: test-create-from-ansible
        password: admin123
        url: http://172.31.90.183:8080
        user: admin