sjobs:
  - { git_repo_url: https://github.com/SandeepNainala/roboshop-terraform.git, job_name: roboshop-terraform }
  - { git_repo_url: https://github.com/SandeepNainala/roboshop-ansible.git, job_name: roboshop-ansible }
  - { git_repo_url: https://github.com/SandeepNainala/aws-ssm-parameter-store.git, job_name: aws-ssm-parameter-store }

mjobs:
    - { git_repo_url: https://github.com/SandeepNainala/cart.git, job_name: cart }